name: Default Issue Template
description: Standard template for creating new issues
title: "[Type] "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
        
        Please start your issue title with an action verb, for example:
        ✅ "Add drippi.ai automation to Marketing Tech Stack"
        ✅ "Implement user authentication system"
        ✅ "Update landing page design"

  - type: textarea
    id: background
    attributes:
      label: Background Information
      description: Provide context and background for this issue
      placeholder: Explain the context and why this issue is needed...
    validations:
      required: true

  - type: textarea
    id: completion-criteria
    attributes:
      label: Completion Criteria
      description: List the specific requirements that need to be met
      placeholder: |
        - [ ] Deliverable specification...
        - [ ] Measurable goal/metric...
        - [ ] Additional requirements...
    validations:
      required: true

  - type: dropdown
    id: time-estimate
    attributes:
      label: Time Estimate
      description: Select the estimated time to complete this task
      multiple: false
      options:
        - "time: < 1 day"
        - "time: 1-2 days"
        - "time: 3-5 days"
        - "time: 1-2 weeks"
        - "time: 2+ weeks"
    validations:
      required: true

  - type: textarea
    id: relevant-links
    attributes:
      label: Relevant Links
      description: Add any relevant links or references
      placeholder: |
        - [Description of link](URL)
        - [Description of link](URL)
        - [Description of link](URL)
    validations:
      required: false
